# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Copy package files
COPY package*.json ./

# Install dependencies without running prepare scripts
RUN npm install --ignore-scripts

# Copy source code
COPY . .

# Build the TypeScript code
RUN npm run build

# Ensure the entrypoint is executable (already set in prepare, but reensure here)
RUN chmod +x dist/index.js

EXPOSE 3000

# Start the MCP server with environment variable mapping
# Append /rest to the server URL if not already present
CMD node dist/index.js
