name: CI – Build & Push GHCR

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - 'Dockerfile'
      - '.github/workflows/ci-cd.yml'

jobs:
  build-push:
    runs-on: ubuntu-latest

    # Grant minimal rights: read repo content + write to GitHub Container Registry
    permissions:
      contents: read
      packages: write

    steps:
      # 1 Checkout repo
      - name: Checkout source
        uses: actions/checkout@v4

      # 2 Node JS (use same major version as lokální build)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.16.0'
          cache: npm

      # 3 Install deps
      - name: Install dependencies
        run: npm ci

      # 4 Generate OpenAPI client code
      - name: Generate code from OpenAPI spec
        run: npm run generate

      # 5 Lint
      - name: Lint
        run: npm run lint

      # 6 Build TypeScript → dist/
      - name: Build
        run: npm run build

      # 7 Run tests
      - name: Test
        run: npm test

      # 8 Login to GHCR with built‑in GitHub token (no extra secret needed)
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 9 Enable Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 10 Build & push image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/bitbucket-mcp-server:latest
            ghcr.io/${{ github.repository_owner }}/bitbucket-mcp-server:${{ github.sha }}
